
AliasMatch ^/mindie-agent/profile$ /usr/src/mindie-agent/profile.php
<Location /mindie-agent/>
	SetEnv MIndieAgent "MIndie-Agent (https://github.com/carrvo/mindie-agent) curl/8.5.0"
	SetEnv MIndieAgentTitle MIndie-Agent
</Location>

AliasMatch ^/mindie-agent/agent$ /usr/src/mindie-agent/agent-instance.php

<Directory /usr/src/mindie-agent/>
	<Files profile.php>
		Require all granted
	</Files>
	<Files agent.php>
		Require all granted
	</Files>
	<Files agent-instance.php>
		Require all granted
	</Files>
</Directory>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
