
# The agent endpoint is an example whose input and output are funneled through a browser.
# Typically the agent component is expected to be a headless process.
# The required configuration is the idp endpoint and the MIndieAgentPath environment variables.

AliasMatch ^/mindie-agent/idp$ /usr/src/mindie-agent/idp.php
AliasMatch ^/mindie-agent/agent$ /usr/src/mindie-agent/agent-instance.php
<LocationMatch ^/mindie-agent/(idp|agent)$>
	# Required - this is the path to your idp endpoint that identifies your agent.
	# Your agent will be required to have this as well.
	SetEnv MIndieAgentPath "/mindie-agent/idp"
	# Optional (only agent) - customize the agent string that outgoing requests identify as.
	SetEnv MIndieAgentAgent "MIndie-Agent (https://github.com/carrvo/mindie-agent) curl/8.5.0"
	# Optional - give a title for your agent's public profile. Not used for the agent component.
	SetEnv MIndieAgentTitle MIndie-Agent
</LocationMatch>

<Directory /usr/src/mindie-agent/>
	<Files agent.php>
		Require all granted
	</Files>
	<Files agent-instance.php>
		Require all granted
	</Files>
</Directory>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
