
AliasMatch ^/mindie-agent/idp$ /usr/src/mindie-agent/idp.php
AliasMatch ^/mindie-agent/agent$ /usr/src/mindie-agent/agent-instance.php
<LocationMatch ^/mindie-agent/(idp|agent)$>
	SetEnv MIndieAgentPath "/mindie-agent/idp"
	SetEnv MIndieAgentAgent "MIndie-Agent (https://github.com/carrvo/mindie-agent) curl/8.5.0"
	SetEnv MIndieAgentTitle MIndie-Agent
</LocationMatch>

<Directory /usr/src/mindie-agent/>
	<Files agent.php>
		Require all granted
	</Files>
	<Files agent-instance.php>
		Require all granted
	</Files>
</Directory>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
